apiVersion: apps/v1
kind: Deployment
metadata:
  name: php56-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php56-app
  template:
    metadata:
      labels:
        app: php56-app
    spec:
      containers:
      - name: php56-container
        image: localhost:5000/phpn-php5.6:0.0.1
        ports:
        - containerPort: 80 # Assuming php56 runs on port 80

---
apiVersion: v1
kind: Service
metadata:
  name: php56-service
spec:
  selector:
    app: php56-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
